spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    rest:
      base-path: /api
server:
  port: 8080